Patched a few bugs (ldv)

diff --git a/ports/xap/epdfview/SlackBuild b/ports/xap/epdfview/SlackBuild
--- a/ports/xap/epdfview/SlackBuild
+++ b/ports/xap/epdfview/SlackBuild
@@ -12,7 +12,7 @@ PKG=$TMP/package-$NAME
 
 VERSION=0.1.5
 ARCH=${ARCH:-i486}
-BUILD=2ldv
+BUILD=3ldv
 
 if [ "$ARCH" = "i386" ]; then
   SLKCFLAGS="-O2 -march=i386 -mcpu=i686"
@@ -30,6 +30,12 @@ cd $TMP
 tar xjvf $CWD/epdfview-$VERSION.tar.bz2
 cd epdfview-$VERSION
 chown -R root.root .
+#+prepare
+for _patch in $CWD/patch-* ; do
+   zcat ${_patch} | patch -p1 || { echo "Applying patch \"${_patch}\" failed" ; exit 1 ; }
+done
+sed -e 's/popppler/poppler/g' -i configure
+#+prepare
 CFLAGS="$SLKCFLAGS" \
 CXXFLAGS="$SLKCFLAGS" \
 ./configure \
@@ -40,7 +46,7 @@ CXXFLAGS="$SLKCFLAGS" \
   $ARCH-slackware-linux
 make
 make install DESTDIR=$PKG
-rm -rf $PKG/usr/info/dir
+rm -fv $PKG/usr/info/dir
 ( cd $PKG
   find . | xargs file | grep "executable" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
   find . | xargs file | grep "shared object" | grep ELF | cut -d : -f 1 | xargs -r strip --strip-unneeded
