Release 0.38test17.

diff --git a/ports/testing/portpkg/autoport b/ports/testing/portpkg/autoport
--- a/ports/testing/portpkg/autoport
+++ b/ports/testing/portpkg/autoport
@@ -1,4 +1,5 @@
-#!/bin/sh -u
+#!/bin/sh
+# -u
 #
 # Autoport -- An Automatic SlackBuild Generator
 # Copyright (C) 2004, 2005 Thomas Pfaff <topf@users.berlios.de>
@@ -17,6 +18,9 @@
 # along with this program; if not, write to the Free Software
 # Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 
+# BUGS:
+#  * "-g xxx" doesn't work sometimes
+
 . `which portpkg` || exit 1
 
 # defaults
@@ -29,7 +33,7 @@ arch=$ARCH
 #build=""
 build_pkg=false
 move_path=""
-output=/dev/null
+#output=/dev/null
 
 ask() # var text
 {
@@ -101,7 +105,7 @@ add_inst() # rel/path/to/command_to_add file
   if ! grep -sq "$s1" $2; then
     row "Adding $s1 to $s2"
     echo "if [ -x `echo $1 | cut -d " " -f 1` ]; then" >>$2
-    echo "  $1 >/dev/null 2>&1" >>$2
+    echo "  $1 2>&1" >>$2
     echo "fi" >>$2
   fi
 }
@@ -124,10 +128,10 @@ remove_inst() # command_to_remove file
 
 init_autoport()
 {
-  is_root || die
+#  is_root || die
   is_defined MY_TAG || die
 
-  args=`getopt -qo "Vav:g:n:u:bh" -- "$@"`
+  args=`getopt -qo "Vav:g:p:n:u:bh" -- "$@"`
   [ "$?" = "0" ] || die "Bad arguments! Try: autoport -h"
   eval set -- "$args"
 
@@ -137,8 +141,8 @@ init_autoport()
       -a) i_act=false;;
       -v) version=$2
           shift;;
-      -V) VERBOSE=true
-          output=/dev/stdout;;
+      -V) VERBOSE=true;;
+#          output=/dev/stdout;;
       -g) group=`echo $2 | cut -d / -f 1`
           shift
           [ "$path" ] && move_path=$path;;
@@ -156,10 +160,10 @@ init_autoport()
 Usage: autoport [options] [source]
 Options:
   -a             Run non-interactive (use defaults)
-  -n name        Preset name of port
-  -v version     Preset version of port
-  -g group       Preset group of port
-  -u port        Re-use settings of existing port
+  -n name        Preset name of new port
+  -v version     Preset version of new port
+  -g group       Preset group of new port
+  -u port        Re-use settings of existing port (\`.' for current dir)
   -b             Execute portpkg after port generation
   -V             Verbose output
 Source:
@@ -182,7 +186,7 @@ EOF
 
 collect_info()
 {
-  $i_act && stanza "Autoport -- An Automatic SlackBuild Generator
+  ask s "Autoport -- An Automatic SlackBuild Generator
 Copyright (C) 2004, 2005 Thomas Pfaff <topf at users dot berlios dot de>
 Autoport comes with ABSOLUTELY NO WARRANTY. This is free software, and you
 are welcome to redistribute it under certain conditions.
@@ -190,30 +194,36 @@ are welcome to redistribute it under certain conditions.
 Autoport is quite experimental. A source code URL given, it will download and
 unpack the code and searche for different keywords to adjust a suitable
 SlackBuild script. If autoport doesn't work as expected, please mail at:
-<topf at users dot berlios dot de>"
+<topf at users dot berlios dot de>
 
-  ask s "* First step: Collect information. Continue? (ctrl-c to quit)"
+* First step: Collect information. Continue? (ctrl-c to quit)"
 
   # sources
   ask s "Source file URL [$sources]:"
   sources=${s:-$sources}
   [ "$sources" ] || die "Nothing entered. Eh? I can't help you this way!"
+  # auto-correct sourceforge.net url if cut-n-pasted
   sources=`echo "$sources" | sed -e "s,://prdownloads\.,://dl.," -e "s,\?download$,,"`
+  # auto-correct GNOME urls later (see version)
   # we can only handle _one_ source file here
   src=`echo "$sources" | head -n 1`
-  # name: guess it, if we haven't yet it
+
+  # guess name by source file name
   file=`basename $(decode $src)`
-  raw_name=`echo $file | rev | cut -d - -f 2- | rev`
+  # (watch out for rarely used form "bla-1.0-src.tar.gz"!)
+  raw_name=`echo $file | sed "s,-src\([\.-]\),\1," | rev | cut -d - -f 2- | rev`
   [ "$name" ] || name=`echo $raw_name | tr "A-Z" "a-z"`
   ask s "Name [$name]:"
   name=${s:-$name}
-  # group
+
+  # group (local/ if nothing else given)
   ask s "Group [$group]:"
   group=${s:-$group}
-  # version
+
+  # guess version
   if ! [ "$version" ]; then
     # version: should be always guessed
-    version=`echo $file | rev | cut -d - -f 1 | rev`
+    version=`echo $file | sed "s,-src\.,.," | rev | cut -d - -f 1 | rev`
     version=`basename $version .tar.gz`
     version=`basename $version .tar.bz2`
     version=`basename $version .tgz`
@@ -223,26 +233,35 @@ SlackBuild script. If autoport doesn't work as expected, please mail at:
   version=${s:-$version}
   srcver=$version
   version=`echo $version | sed "s,-,,g"`
+  # auto-correct path in GNOME urls: http://.../name/2.12/name-2.12.0.tar.gz
+  sver=`echo $version | cut -s -d . -f 1-2`
+  [ "$script" ] && old_sver=`grep ^VERSION= $script | cut -d = -f 2 | cut -s -d . -f 1-2 | sed "s,\.,\.,"`
+  [ "$sver" ] && [ "$old_sver" ] \
+  && sources=`echo "$sources" | sed -e "s,/$old_sver/,/$sver/,g"`
+
   # arch
   ask s "Arch [$arch]:"
   arch=${s:-$arch}
-  # build: check if we need to increment
+
+  # build: increment if exactly this package is already in the ports
   n=1
-  gpkg=`ls_scr | scr2virt | virt2gpkg | grep -m 1 "^$group/$name-$version-[^-]*-[^-]*$"`
+#  gpkg=`ls_scr | scr2virt | any2gpkg | grep -m 1 "^$group/$name-$version-[^-]*-[^-]*$"`
+  gpkg=`ls_virt "/$group/$name-$version-[^-]*-[^-]*$" | any2gpkg | head -n 1`
   if [ $gpkg ]; then
-    $i_act && stanza "There is already $group/$name-$version."
+    $i_act && stanza "There is already a $name-$version port in $group/."
     n=`echo $gpkg | pkg2rel | cut -d - -f 3 | sed "s,[a-z]*$,,"`
     # now that we found it, we can find a bigger number too!
     n=`expr $n + 1`
   fi
   ask s "Build [$n$MY_TAG]:"
   build=${s:-$n$MY_TAG}
+
   # desc
   if [ "$description" ]; then
-    desc1=`echo "$description" | sed "s,^$name:[ ]*,," | head -n 1`
-    desc2=`echo "$description" | sed "s,^$name:[ ]*,," | sed "1,2d"`
+    desc1=`echo "$description" | sed "s,^$name: *,," | head -n 1`
+    desc2=`echo "$description" | sed "s,^$name: *,," | sed "1,2d"`
   else
-    desc1=$raw_name
+    desc1="$raw_name ($name-$version)"
     desc2=""
   fi
   ask s "Description (1-liner) [$desc1]:"
@@ -268,14 +287,16 @@ $l"
           echo "$desc2" | fmt -u -w $(expr 75 - $len) | sed "s,^,$name: ,"
           for i in 1 2 3 4 5 6 7 8 9; do
             echo "$name:"
-          done; } | head -n 11`
+          done
+        } | head -n 11`
 
 #  if [ "$group" != "local" ] && [ "$script" ]; then
 #    path=`dirname $script`
 #  else
+  if ! [ "$path" ] || [ "$move_path" ]; then
     path=$PRT_DIR/$group/$name
     script=$path/SlackBuild
-#  fi
+  fi
 
   if $i_act; then
     echo
@@ -305,16 +326,19 @@ prepare_port()
     cp -a $move_path/* $path/
   fi
 
-  if [ -f $path/stop.autoport ]; then
+  if [ -f $path/stop.autoport ] || grep -sq "^# autoport-stop:" $script; then
     stanza "There's a warning not to autoport this source code:"
     echo "==========================================="
-    cat $path/stop.autoport
+    [ -f $path/stop.autoport ] && cat $path/stop.autoport \
+    || grep "^# autoport-stop:" $script | cut -d " " -f 3-
     echo "==========================================="
     die
   fi
 
   if [ -d $path ]; then
     ask s "* This port ($path) already exists. Really go on? (ctrl-c to quit)"
+    # make a copy
+    cp $script $script.autoport-backup
   fi
 }
 
@@ -323,6 +347,19 @@ port()
   stanza "Autoporting $group/$name-$version-$arch-$build:"
   mkdir -p $path
   touch $script
+
+#  # if we have a checksum of the last autoport, check it
+#  if grep -sq "^# autoport-checksum:" $script; then
+#    sed "/^# autoport-checksum:/d" $script >$t/script.orig
+#    local md5sum=`grep "^# autoport-checksum:" $script | cut -d " " -f 3`
+#    if ! echo "$md5sum  $t/script.orig" | md5sum -c >&2; then
+#      error "This script has been manually changed after last auto-porting! Autoport cannot
+#assure to work correctly with this script. You can override this error by
+#removing the line starting with \`# autoport-checksum:' in $script!"
+#      exit 1
+#    fi
+#    cat $t/script.orig >$script
+#  fi
 
   # first convert old tags ("#+...-fix")...
   sed -i "s,^#+post-doc-fix$,#+docfiles,g" $script
@@ -361,6 +398,7 @@ port()
   done
 
   # downlaod source files
+  maintain=true
   find $path/ -type l -exec rm -rf {} \;
   get_sources || die
 
@@ -377,7 +415,7 @@ port()
   echo -n "  --> Checking format... "
   mkdir -p $t/src
 #  case $file in
-  file=`basename $(echo "$sources" | head -n 1)`
+  file=`basename $(echo "$sources" | head -n 1 | cut -d % -f 2)`
   case `echo "$sources" | head -n 1` in
     *.tar.bz2)
       format=tarbz2
@@ -436,11 +474,13 @@ port()
     fi
     srcdir_prefix_out=`encode "$srcdir_prefix"`
     sed -i "s,%srcdirprefix%,$srcdir_prefix_out," $script
+    sed -i "s,%docdir%,$srcdir_prefix_out," $script
   else
     echo "no prefix"
     snip cd_sdp $script
     srcdir_prefix="."
     sed -i "s,%srcdirprefix%,\$NAME-\$VERSION," $script
+    sed -i "s,%docdir%,\$NAME-\$VERSION," $script
     mkdir $t/src/$name-$version
     mv $t/src/* $t/src/$name-$version
     rm -rf $TMP/$name-$version
@@ -512,7 +552,7 @@ port()
       snip configure $script
       snip make_PREFIX $script
       snip make_prefix $script
-      arch=noarch
+#      arch=noarch
     else
       snip perl $script
 #      if check "^configure(|\.in|\.in\.in)$" $t/footprint; then
@@ -528,6 +568,7 @@ port()
         fi
         check "--program-prefix" $TMP/$srcdir_prefix/configure* || snip configure_program_prefix $script
         check "--disable-static" $TMP/$srcdir_prefix/configure* || snip configure_disable_static $script
+        check "--disable-scrollkeeper" $TMP/$srcdir_prefix/configure* || snip configure_disable_scrollkeeper $script
         snip autogen $script
         snip make_prefix $script
         snip make_PREFIX $script
@@ -552,9 +593,10 @@ port()
         else
           snip make_prefix $script
           snip make_PREFIX $script
-          if check "^setup\.py$" $t/footprint; then
-            arch=noarch
-          else
+#          if check "^setup\.py$" $t/footprint; then
+#            arch=noarch
+#          else
+          if ! check "^setup\.py$" $t/footprint; then
             snip python $script
             warn "Don't know how to configure this package."
           fi
@@ -671,7 +713,14 @@ port()
   else
 #    remove_inst "update-desktop-database" $path/doinst.sh
     grep -sq "update-desktop-database" $path/doinst.sh \
-    && warn "update-desktop-database seems removed. Please check!"
+    && warn "update-desktop-database seems obsolete. Please check!"
+  fi
+
+  # gdk-pixbuf-query-loaders
+  if check "gdk-pixbuf-query-loaders" $TMP/$srcdir_prefix/*; then
+    add_inst "usr/bin/gdk-pixbuf-query-loaders >etc/gtk-2.0/gdk-pixbuf.loaders" $path/doinst.sh
+  else
+    remove_inst "gdk-pixbuf-query-loaders" $path/doinst.sh
   fi
 
   # config() subroutine needed?
@@ -704,9 +753,10 @@ port()
       snip strip $script;;
     *)
       # we know better than the user ;-)
-      grep -sq SLKCFLAGS $script \
-      && sed -i "s,%arch%,\${ARCH:-i486}," $script \
-      || sed -i "s,%arch%,$arch," $script;;
+#      grep -sq SLKCFLAGS $script \
+#      && sed -i "s,%arch%,\${ARCH:-i486}," $script \
+#      || sed -i "s,%arch%,$arch," $script;;
+      sed -i "s,%arch%,\${ARCH:-i486}," $script
   esac
 
   # clean up
@@ -726,14 +776,21 @@ port()
   fi
 
   # any errors?
-  $failed && die "There's been an error. Please write SlackBuild manually."
+  $failed && die "There's been an error. Please write SlackBuild manually (see $TMP/$srcdir_prefix/)."
+
+  # success, success!!
+  rm -f $script.autoport-backup
+
+#  # write checksum
+#  md5sum $script | cut -d " " -f 1 | xargs echo "# autoport-checksum:" >>$script
 
   # portpkg?
   if $build_pkg; then
     ask s "* Next step: Call portpkg. Continue? (ctrl-c to quit)"
     # ok, if this port is new, it has no dependencies, if it's rewritten,
     # let's assume, the user wants to rebuild only this port
-    VERBOSE=$VERBOSE portpkg -q $group/$name
+    cd $path
+    VERBOSE=$VERBOSE portpkg -b #-q $group/$name
 #    # we have changed the ports tree
 #    rm -rf $SCR_CACHE $LOC_CACHE $PKG_CACHE
 #    NO_REQS=true
@@ -741,10 +798,10 @@ port()
   fi
 }
 
-init_autoport "$@"
-collect_info 2>$output
-prepare_port 2>$output
-port 2>$output
+init_autoport "$@" #2>$output
+collect_info #2>$output
+prepare_port #2>$output
+port #2>$output
 exit 0
 
 #----------------------------------------
@@ -804,6 +861,7 @@ CXXFLAGS="$SLKCFLAGS" \ ##cxxflags
   --localstatedir=/var/lib \ ##configure_localstatedir
   --program-prefix="" \ ##configure_program_prefix
   --disable-static \ ##configure_disable_static
+  --disable-scrollkeeper \ ##configure_disable_scrollkeeper
   $ARCH-slackware-linux
 #:configure
 #%post-configure%
@@ -841,11 +899,11 @@ chown -R root.bin $PKG/%prefix%/bin $PKG/%prefix%/sbin || true
 #:doc
 mv $PKG/usr/share/man $PKG/usr/share/doc $PKG/usr/ || true
 gzip -9 $PKG/usr/info/* $PKG/usr/man/man?/* $PKG/usr/man/*/man?/* || true
-mkdir -p $PKG/usr/doc/$NAME-$VERSION
+mkdir -p $PKG/usr/doc/%docdir%
 #:docfiles
 cp -a \
   %docs% \
-  $PKG/usr/doc/$NAME-$VERSION/
+  $PKG/usr/doc/%docdir%/
 #:docfiles
 #%post-docfiles%
 find $PKG/usr/doc -type f -exec chmod 644 {} \;
