Create new md5sums right after download, not in maintainer_mode().

diff --git a/ports/d/portpkg/portpkg b/ports/d/portpkg/portpkg
--- a/ports/d/portpkg/portpkg
+++ b/ports/d/portpkg/portpkg
@@ -353,9 +353,9 @@ maintainer_mode()
 #  rm -rf md5sums
 #  rm -rf footprint
 
-  # md5sum only source files, which are symlinks here
-  find . -type l | sed "s,^\./,," | sort | xargs -r md5sum >>md5sums
-  sort +1 -uo md5sums md5sums
+#  # md5sum only source files, which are symlinks here
+#  find . -type l | sed "s,^\./,," | sort | xargs -r md5sum >>md5sums
+#  sort +1 -uo md5sums md5sums
 
 #  # sign md5sums
 #  if [ -d ~/.gnupg ] && [ `which gpg` ]; then
@@ -460,10 +460,16 @@ build_pkg()
     if ! $DRY_RUN; then
       ln -s $SRC_DIR/$srcname .
       # check md5sums when non-maintainer-mode
-      if ! $maintain && grep -sq " $srcname$" md5sums \
-      && ! grep " $srcname$" md5sums | md5sum -c --status 2>/dev/null; then
-        error "Integrity checking failed: $srcname"
-        return 1
+      if $maintain; then
+        md5sum $srcname >>md5sums
+        sort +1 -uo md5sums md5sums
+      elif grep -sq " $srcname$" md5sums; then
+        if ! grep " $srcname$" md5sums | md5sum -c --status 2>/dev/null; then
+          error "Integrity checking failed: $srcname"
+          return 1
+        fi
+      else
+        warn "No checksums available for $srcname!"
       fi
     fi
   done
