Fixed testing for existence of directories. [ -d $var ] is always true, if $var is a nullstring.

diff --git a/ports/d/portpkg/portpkg b/ports/d/portpkg/portpkg
--- a/ports/d/portpkg/portpkg
+++ b/ports/d/portpkg/portpkg
@@ -96,7 +96,7 @@ debug()  { $DEBUG && echo "$@" >&2; }
 has_args()  { [ "$*" ] || error "Too few arguments! Try: portpkg --help"; }
 is_root()   { [ "$UID" == "0" ] || error "You must be root to run this action!"; }
 has_prog()  { which $1 >/dev/null 2>&1 || error "Cannot find $1!"; }
-has_ports() { [ -d $PRT_DIR ] || error "No ports found! Try: portpkg --sync"; }
+has_ports() { [ -d "$PRT_DIR" ] || error "No ports found! Try: portpkg --sync"; }
 
 # cache the output of "action" and grep a regex
 cache() # file action regex
@@ -768,7 +768,7 @@ do_sync()
   # unhide .CVS
   find $PRT_DIR/ -name .CVS -depth -exec dirname {} \; | xargs -i mv {}/.CVS {}/CVS
 
-  if [ -d $PRT_DIR ]; then
+  if [ -d "$PRT_DIR" ]; then
     cd $PRT_DIR || die
     cvs -qz9 up -dP -I local -I 0 -I z 2>/dev/null
   else
@@ -932,7 +932,7 @@ maintain,export:"
 init()
 {
   # make temporary directory
-  [ -d $TMPDIR ] || die "Internal error!"
+  [ -d "$TMPDIR" ] || die "Internal error!"
 
   # clean up on exit
   trap "rm -rf $TMPDIR" EXIT
