Moved local/portpkg-0.36-noarch-1tom to d/.

diff --git a/ports/d/portpkg/pp-config b/ports/d/portpkg/pp-config
--- a/ports/d/portpkg/pp-config
+++ b/ports/d/portpkg/pp-config
@@ -15,17 +15,17 @@ target()
 If unsure enter '$newest_slack'." 0 0 \
     "$DIST_VER" 2>$t/dist-ver || exit
   DIST_VER=`cat $t/dist-ver`
-  sed -i "/^DIST_VER=/d" $PRT_DIR/local.conf
+  sed -i "/^DIST_VER=/d" $CFG_DIR/local.conf
   if [ "$DIST_VER" ]; then
-    echo "DIST_VER=\"$DIST_VER\"" >>$PRT_DIR/local.conf
+    echo "DIST_VER=\"$DIST_VER\"" >>$CFG_DIR/local.conf
     if [ $DIST_VER == $newest_slack ] || [ $DIST_VER == current ]; then
       if dialog --title "$heading" --yesno \
 "It is recommended to exclude ports of the group pasture/. Shall I add \
-'pasture/' to your exclude list ($PRT_DIR/exclude.local)?
+'pasture/' to your exclude list ($CFG_DIR/exclude.local)?
 If unsure answer 'yes'." 0 0; then
         # add pasture/ to the list of excluded ports
-        sed -i "/^pasture\/$/d" $PRT_DIR/exclude.local
-        echo "pasture/" >>$PRT_DIR/exclude.local
+        sed -i "/^pasture\/$/d" $CFG_DIR/exclude.local
+        echo "pasture/" >>$CFG_DIR/exclude.local
       fi
     fi
   fi
@@ -39,22 +39,22 @@ maintain()
 letters allowed (e.g. 'mich').
 Leave this empty if unsure or you don't plan to write ports." 0 0 "$MY_TAG" 2>$t/my-tag || exit
   MY_TAG=`cat $t/my-tag | tr "A-Z" "a-z" | sed "s,[^a-z],,g"`
-  sed -i "/^MY_TAG=/d" $PRT_DIR/local.conf
-  sed -i "/^MY_EMAIL=/d" $PRT_DIR/local.conf
-  sed -i "/^MY_REALNAME=/d" $PRT_DIR/local.conf
+  sed -i "/^MY_TAG=/d" $CFG_DIR/local.conf
+  sed -i "/^MY_EMAIL=/d" $CFG_DIR/local.conf
+  sed -i "/^MY_REALNAME=/d" $CFG_DIR/local.conf
   if [ "$MY_TAG" ]; then
-    echo "MY_TAG=\"$MY_TAG\"" >>$PRT_DIR/local.conf
+    echo "MY_TAG=\"$MY_TAG\"" >>$CFG_DIR/local.conf
     dialog --title "$heading" --inputbox \
 "If you plan to contrib your ports to the Portpkg Project, you need to enter \
 your mail address.
 Leave this empty if you don't plan to contribute ports." 0 0 "$MY_EMAIL" 2>$t/my-email || exit
     MY_EMAIL=`cat $t/my-email`
     if [ "$MY_EMAIL" ]; then
-      echo "MY_EMAIL=\"$MY_EMAIL\"" >>$PRT_DIR/local.conf
+      echo "MY_EMAIL=\"$MY_EMAIL\"" >>$CFG_DIR/local.conf
       dialog --title "$heading" --inputbox \
 "Please enter your real name." 0 0 "$MY_REALNAME" 2>$t/my-realname || exit
       MY_REALNAME=`cat $t/my-realname`
-      echo "MY_REALNAME=\"$MY_REALNAME\"" >>$PRT_DIR/local.conf
+      echo "MY_REALNAME=\"$MY_REALNAME\"" >>$CFG_DIR/local.conf
     fi
   fi
 }
@@ -62,19 +62,19 @@ Leave this empty if you don't plan to contribute ports." 0 0 "$MY_EMAIL" 2>$t/my
 output()
 {
   heading="OUTPUT SETTINGS"
-  sed -i "/^VERBOSE=/d" $PRT_DIR/local.conf
+  sed -i "/^VERBOSE=/d" $CFG_DIR/local.conf
   if dialog --title "$heading" --defaultno --yesno \
 "Do you want to have always verbose mode? You will see more output.
 If unsure answer 'no'." 0 0; then
-    echo "VERBOSE=true" >>$PRT_DIR/local.conf
+    echo "VERBOSE=true" >>$CFG_DIR/local.conf
   fi
 }
 
 dependencies()
 {
   heading="DEPENDENCIES SETTINGS"
-  sed -i "/^NO_REQS=/d" $PRT_DIR/local.conf
-  sed -i "/^LAZY_CHECKS=/d" $PRT_DIR/local.conf
+  sed -i "/^NO_REQS=/d" $CFG_DIR/local.conf
+  sed -i "/^LAZY_CHECKS=/d" $CFG_DIR/local.conf
   if dialog --title "$heading" --yesno \
 "Do you want to have dependency resolution always enabled?
 If unsure answer 'yes'." 0 0; then
@@ -83,10 +83,10 @@ If unsure answer 'yes'." 0 0; then
 being upgraded if possible. Lazy upgrading cuts that off, but can cause ports \
 fail to build.
 If unsure answer 'no'." 0 0; then
-      echo "LAZY_CHECKS=true" >>$PRT_DIR/local.conf
+      echo "LAZY_CHECKS=true" >>$CFG_DIR/local.conf
     fi
   else
-    echo "NO_REQS=true" >>$PRT_DIR/local.conf
+    echo "NO_REQS=true" >>$CFG_DIR/local.conf
   fi
 }
 
@@ -107,47 +107,13 @@ If unsure answer 'yes'." 0 0 && use_bin=true
 #Slackware packages better. You will be able to port Slackware package by its \
 #source code scripts. Nevertheless this function is quite unstable.
 #If unsure answer 'no'." 0 0 && use_src=true
-  sed -i "/^BIN_PRT_DIR=/d" $PRT_DIR/local.conf
-  sed -i "/^SRC_PRT_DIR=/d" $PRT_DIR/local.conf
-  sed -i "/^SYNC_ADDON=/d" $PRT_DIR/local.conf
+  sed -i "/^BIN_PRT_DIR=/d" $CFG_DIR/local.conf
+  sed -i "/^SRC_PRT_DIR=/d" $CFG_DIR/local.conf
+  sed -i "/^SYNC_ADDON=/d" $CFG_DIR/local.conf
 #  $use_bin || $use_src || return
-  $use_bin && echo "BIN_PRT_DIR=\$PRT_DIR/z/bin" >>$PRT_DIR/local.conf
-  $use_bin && echo "SYNC_ADDON=\"pp-sync-bin\"" >>$PRT_DIR/local.conf
-#  $use_src && echo "SRC_PRT_DIR=\$PRT_DIR/z/src" >>$PRT_DIR/local.conf
-return
-  ports="Ports $PRT_DIR"
-  bins="Binaries ${BIN_PRT_DIR:-$PRT_DIR/z/bin}"
-  srcs="Source ${SRC_PRT_DIR:-$PRT_DIR/z/src}"
-  local rc=3
-  while [ $rc == 3 ]; do
-    # assume the ports tree comes after its child directory xxx/a
-    ports="$ports/mmm"
-    list=`echo -e "$ports\n$bins\n$srcs" | sort +1`
-    ports=`echo $ports | sed "s,/mmm$,,"`
-    list=`echo "$list" | sed "s,/mmm$,,"`
-    echo "$list"
-    dialog --title "$heading" --extra-label "Change" --inputmenu 
-"Which resources do you prefer?
-You can change the paths of these resources to adjust the order of available \
-ports. It is recommended to use /usr/ports/0/... and /usr/ports/z/...
-If unsure press OK." 20 60 9 $list 2>$t/out
-    rc=$?
-    out=`cat $t/out`
-    if [ $rc == 3 ]; then
-      case $out in
-        RENAMED\ P*)
-          ports=`echo $out | cut -d " " -f 2-`;;
-        RENAMED\ B*)
-          bins=`echo $out | cut -d " " -f 2-`;;
-        RENAMED\ S*)
-          srcs=`echo $out | cut -d " " -f 2-`;;
-      esac
-    fi
-  done
-  BIN_PRT_DIR=`echo $bins | cut -d " " -f 2-`
-  SRC_PRT_DIR=`echo $srcs | cut -d " " -f 2-`
-  $use_bin && echo "BIN_PRT_DIR=$BIN_PRT_DIR" >>$PRT_DIR/local.conf
-  $use_src && echo "SRC_PRT_DIR=$SRC_PRT_DIR" >>$PRT_DIR/local.conf
+  $use_bin && echo "BIN_PRT_DIR=\$PRT_DIR/z/bin" >>$CFG_DIR/local.conf
+  $use_bin && echo "SYNC_ADDON=\"pp-sync-bin\"" >>$CFG_DIR/local.conf
+#  $use_src && echo "SRC_PRT_DIR=\$PRT_DIR/z/src" >>$CFG_DIR/local.conf
 }
 
 mirrors()
@@ -155,45 +121,117 @@ mirrors()
   heading="MIRROR SETTINGS"
   echo -n "dialog --title \"$heading\" --menu \
 \"Which of the currently available mirror files do you want to use?\" 0 0 0 " >$t/menu
-  find $PRT_DIR/mirrors.* | xargs basename | grep -v mirrors.local \
+  find $CFG_DIR/mirrors.* | xargs basename | grep -v mirrors.local \
   | xargs -i echo "{} \"Mirror list\" \\" >>$t/menu
   echo "none \"Use main server URLs\"" >>$t/menu
   . $t/menu 2>$t/out
   out=`cat $t/out`
   rm -rf $PRT_DIR/mirrors
   if [ "$out" != "none" ]; then
-    ln -s $out $PRT_DIR/mirrors
+    ln -s $out $CFG_DIR/mirrors
   fi
+}
+
+cpu()
+{
+  # This subroutine has been "inspired" by the configure script from Mplayer.
+  # Thanks to these people! :-)
+  [ -f /proc/cpuinfo ] || die "Cannot determine CPU without /proc."
+  vendor=`grep "vendor_id" /proc/cpuinfo | cut -d : -f 2 | xargs`
+  family=`grep "cpu family" /proc/cpuinfo | cut -d : -f 2 | xargs`
+  model=`grep "model" /proc/cpuinfo | grep -v "model name" | cut -d : -f 2 | xargs`
+  stepping=`grep "stepping" /proc/cpuinfo | cut -d : -f 2 | xargs`
+  case $vendor in
+    AuthenticAMD)
+      case $family in
+        3) proc=i386;;
+        4) proc=i486;;
+        5) case $model in
+             9|13) proc=k6-3;;
+             8)    proc=k6-2;;
+             6|7)  proc=k6;;
+             *)    proc=i586;;
+           esac;;
+        6) case $model in
+             1|2|3) proc=athlon;;
+             4|5)   proc=athlon-tbird;;
+             6)     case $stepping in
+                      1) proc=athlon-4;;
+                      *) grep -wsq "sse" /proc/cpuinfo \
+                           && proc=athlon-xp \
+                           || proc=athlon-4;;
+                    esac;;
+             *)     proc=athlon-4;;
+           esac;;
+        *) proc=athlon-xp;;
+      esac;;
+    GenuineIntel)
+      case $family in
+        3) proc=i386;;
+        4) proc=i486;;
+        5) case $model in
+             1|2|3) proc=i586;;
+             *)     proc=pentium-mmx;;
+           esac;;
+        6) case $model in
+             1|2)     proc=i686;;
+             3|4|5|6) proc=pentium2;;
+             *)       proc=pentium3;;
+           esac;;
+        *) proc=pentium4;;
+      esac;;
+    *)
+      case $family in
+        3) proc=i386;;
+        4) proc=i486;;
+        *) proc=i586;;
+      esac;;
+  esac
+  echo $proc
 }
 
 optimise()
 {
   heading="OPTIMISATION SETTINGS"
-  dialog --title "$heading" --menu \
-"Which set of optimisations would you like to use? \
-Your running architecture is `arch`. Other than 'default', you will have \
-ARCH=`arch`. Note, that not all SlackBuilds support custom compiler flags. \
-These are common values, if want different flags edit $PRT_DIR/local.conf.
+  case `arch` in
+    s390|x86_64)
+      if dialog --title "$heading" --yesno \
+"Your are running `arch`. You should set ARCH to `arch`. Shall I do that for \
+you?"; then
+        sed -i "\,^ARCH=,d" $CFG_DIR/local.conf
+        echo "ARCH=`arch`" >>$CFG_DIR/local.conf
+      fi;;
+    *)
+      dialog --title "$heading" --menu \
+"Do you want to optimise for your CPU? Your CPU is identified as `cpu` of \
+family `arch`. You can only optimise for your current architecture. If you \
+want to hack on different flags, edit $CFG_DIR/local.conf. Note, that not all \
+SlackBuilds support custom compiler flags.
 If unsure choose 'default'." 0 0 0 \
-    "default"   "Build for i486, optimise for i686" \
-    "`arch`"    "Generic `arch` optimisations" \
-    "athlon"    "Optimise for Athlon/Duron" \
-    "athlon-xp" "Optimise for Athlon XP/Duron Morgan" \
-    "pentium2"  "Optimise for Pentium2/Celeron (Mendocino)" \
-    "pentium3"  "Optimise for Pentium3/Celeron Coppermine" \
-    "pentium4"  "Optimise for Pentium4/Celeron Willamette" \
-    "x86_64"    "Build on x86_64" \
-    "s390"      "Build on s/390" 2>$t/menu
-  [ $? == 0 ] || return
-  sed -i "/^ARCH=/d" $PRT_DIR/local.conf
-  sed -i "/^CFLAGS=/d" $PRT_DIR/local.conf
-  case `cat $t/menu` in
-    default) ;;
-    `arch`)  echo -e "ARCH=`arch`\nCFLAGS=\"-O2 -march=\$ARCH\"";;
-    x86_64)  echo "ARCH=x86_64"; return;;
-    s390)    echo "ARCH=s390"; return;;
-    *)       echo -e "ARCH=`arch`\nCFLAGS=\"-O2 -march=\$ARCH -mcpu=`cat $t/menu`\"";;
-  esac >>$PRT_DIR/local.conf
+    "default"  "Build for i486, optimise for i686" \
+    "optimise" "Build for `arch`, optimise for `cpu`" 2>$t/menu
+      [ $? == 0 ] || return
+      sed -i "/^ARCH=/d" $CFG_DIR/local.conf
+      sed -i "/^CFLAGS=/d" $CFG_DIR/local.conf
+      if [ `cat $t/menu` == optimise ]; then
+        echo "ARCH=`arch`"
+        echo "CFLAGS=\"-O2 -march=`arch` -mcpu=`cpu`\""
+      fi >>$CFG_DIR/local.conf;;
+  esac
+}
+
+paths()
+{
+  heading="PATH SETTINGS"
+  eval "BIN_PRT_DIR=`grep ^BIN_PRT_DIR= $CFG_DIR/local.conf | cut -d = -f 2`"
+  dialog --title "$heading" --extra-label "Change" --inputmenu \
+"Set different values for sources and binaries (.tgz-packages) here:
+If unsure leave as is." 0 0 9 \
+  "sources"  "$SRC_DIR" \
+  `if [ "$BIN_PRT_DIR" ]; then
+    echo "bin-pseudos $BIN_PRT_DIR"
+  fi` \
+  "binaries" "$PKG_DIR" 2>$t/menu
 }
 
 rc=0
@@ -209,6 +247,7 @@ Select what you want to configure:" 0 0 0 \
   mirrors "Set mirrors for downloads" \
   optimise "Set processor optimising" \
   dependencies "Set dependency handling" 2>$t/sub
+#  paths "Set paths for sources and binaries" \
   rc=$?
   sub=`cat $t/sub`
   [ $rc == 0 ] && $sub
