* Moved check_reqs() out of build_pkg() and put into do_add(). * check_reqs(): Prefer package from the USE scope. * check_reqs(): Reverted all this special output for DRY_RUN into (nearly) normal output, since do_add() now prints a reasonable targets list. * do_add(): Check all dependencies recursively and print one final target list and one list of dependencies to consider. * do_add(): Prompt after targets list again. * do_add(): Removed warnings, since targets list is mandatory now.

diff --git a/portpkg/portpkg b/portpkg/portpkg
--- a/portpkg/portpkg
+++ b/portpkg/portpkg
@@ -85,7 +85,7 @@ INST_DIR=$ADM_DIR/packages
 CFG_DIR=/etc/portpkg
 PATH=$PATH:/sbin:/usr/local/sbin:/usr/sbin
 ENGINE_VER=cvs
-ENGINE_REV="\$Revision: 1.14 $"
+ENGINE_REV="\$Revision: 1.15 $"
 TMPDIR=`mktemp -d $TMP/portpkg-XXXXXX` || exit 1
 export TMPDIR
 CACHE=`mktemp -d`
@@ -578,7 +578,7 @@ echo $inst_pkg; } | default`
       list_add opts "$req"
     # anyway, is there an available port?
     elif [ "${avail_pkg:-$use_pkg}" ]; then
-      avail_pkg=${avail_pkg:-$use_pkg}
+      avail_pkg=${use_pkg:-$avail_pkg}
       debug "check_reqs(): $name: $req: mismatch [${inst_pkg:-not installed}]"
       # move if previously marked as optional
       if in_list opts "$req"; then
@@ -587,18 +587,10 @@ echo $inst_pkg; } | default`
       fi
       # if there's already one missing go straight on to the next
       [ -s $CACHE/list_miss ] && continue
-      $DRY_RUN && ! [ "${prev:-}" ] && ! $DOWNLOAD_ONLY && stanza "Preparing dependencies of $package:"
       prev=$name
       list_add prev "$group/$name"
-      ( if $DRY_RUN; then
-          stanza() { :; }
-          header() { :; }
-        fi
-#        get_info ${avail_pkg%-*-*-*} || exit 1
-        get_info $avail_pkg || die
-        add_pkg || die "${avail_pkg##*/} failed! Stopping $prev."
-        $DRY_RUN && ! $DOWNLOAD_ONLY && ! $PREPARE_ONLY && row "$install_msg"
-        exit 0
+      ( get_info ${avail_pkg%-*-*-*} || exit 1
+        check_reqs || die "${avail_pkg##*/} failed! Stopping $prev."
       ) || return 1
       list_del prev "$group/$name"
       pkg_file=`find_pkg_file`
@@ -757,10 +749,6 @@ build_pkg()
   local t=`mktemp -d`
   local src srcname dest md5sum script_opt flags_var sh_opt prod build_cmd products
 
-  # requirements check
-  check_reqs || return 1
-  [ -s $CACHE/list_opts ] && warn "Optional dependencies to consider:" `cat $CACHE/list_opts`
-
   # package file found in cache?
   if [ "$pkg_file" ] && ! $rebuild; then
     $DOWNLOAD_ONLY && row "$package.tgz found in ${pkg_file%/*}/" && return 0
@@ -794,7 +782,7 @@ build_pkg()
 
   case `pause "Continue: $build_msg? (s to skip)"` in s|S) continue;; esac
   
-  $DOWNLOAD_ONLY || header "Processing $group/$name"
+  $DOWNLOAD_ONLY || $DRY_RUN || header "Processing $group/$name"
   $DOWNLOAD_ONLY || stanza "$build_msg:"
 
   cd ${script%/*} || return 1
@@ -1069,16 +1057,23 @@ do_add() # pkgex-list
 
   # add targets to USE scope
   USE="${USE:+$USE }$@"
+
+  # pre-run for requirements check
+  if ! $NO_REQS; then
+    stanza "Checking dependencies..."
+    for arg in $targets; do
+      ( get_info $arg || die
+        check_reqs
+      ) || return 1
+    done
+    [ -s $CACHE/list_opts ] && warn "Optional dependencies to consider:" `cat $CACHE/list_opts`
+    targets=`cat $CACHE/list_reqs`
+  fi
   
   # if we have implicit expressions here (groups), tell what they contain
   if [ `echo "$targets" | wc -l` != `echo "${@:-.}" | wc -w` ]; then
-    warn "You are using an implicit expression. Use with caution!"
-    if ! $NO_REQS && ! $TEST_REQS; then
-      warn "Exact results are NOT COMPLETELY predictable. \
-Try --dryrun first and consider using --noreqs and/or --ignore!"
-    fi
-    
     stanza "Targets: "`echo "$targets" | sed "s,.*/,,"`
+    pause "Continue? (ctrl-c to abort)"
   fi
 
   $DOWNLOAD_ONLY && stanza "Downloading files:"
